@startuml admin_page

title Admin User Modification

actor Admin #red
participant Frontend
participant Backend
database Database

Admin -> Frontend ++: Ask for all users
Frontend -> Backend ++: GET /api/admin/user
Backend -> Backend: Validate JWT
Backend -> Database ++: Fetch all users
Database --> Backend --: Return all users
Backend --> Frontend --: Return all users
Frontend --> Admin --: Table with all users

Admin -> Frontend ++: Click button to change a user's credentials
Frontend --> Admin --: Form with user's credentials
Admin -> Frontend ++: Submit form with user's changed credentials
Frontend -> Backend ++: PUT /api/admin/user/:id with changedUser JSON and JWT

Backend -> Backend: Validate JWT (Admin)
Backend -> Backend: Validate user's modified credentials
Backend -> Database ++: Modify user

Database --> Backend --: Update Message
Backend --> Frontend --: Modify Message

alt successful modification

Frontend -> Frontend: Update users store / reactive update

end

Frontend --> Admin --: Notify admin for successful/unsuccessful operation

@enduml